name: Build

on:
  push:
    branches:
      - golang

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      - name: Build
        run: make PLUGIN_TAG=${{ steps.vars.outputs.tag }} plugin

      - name: Push
        run: make PLUGIN_TAG=${{ steps.vars.outputs.tag }} push
